[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/__/auth/*"
  to = "https://stalwart-circlet-8jk7s.firebaseapp.com/__/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
